language: python
python:
  - "3.7"
before_install:
  - openssl aes-256-cbc -K $encrypted_099a44ce718c_key -iv $encrypted_099a44ce718c_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
  - pip install -e .
# command to run tests
script:
  - make test
  - make test-gravitate
after_success:
  - coveralls
notifications:
  email: false