language: python
python:
  - "3.6"
  - "3.7-dev"
before_install:
  - openssl aes-256-cbc -K $encrypted_099a44ce718c_key -iv $encrypted_099a44ce718c_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
  - tar xvf credentials.tar.gz -C tests/config_jsons
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest tests
notifications:
  email: false