language: python
python:
  - "3.7-dev"
before_install:
  - openssl aes-256-cbc -K $encrypted_099a44ce718c_key -iv $encrypted_099a44ce718c_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
  - mkdir config_jsons
  - tar xvf credentials.tar.gz -C config_jsons
  # Configure gravitate-backend example
  - pip insall -e .
  - pip install -r gravitate-backend/requirements.txt
  - pip install -r gravitate-backend/requirements-dev.txt
  - openssl aes-256-cbc -K $encrypted_2240fe55269d_key -iv $encrypted_2240fe55269d_iv -in gravitate-backend/gravitate-backend-testing-firebase-adminsdk-nztgj-d063415ecc.json.enc -out gravitate-backend/gravitate/config_jsons/gravitate-backend-testing-firebase-adminsdk-nztgj-d063415ecc.json -d

# command to run tests
script:
  - make test
after_success:
  - coveralls
notifications:
  email: false