language: python
python:
  - "3.7-dev"
before_install:
  - openssl aes-256-cbc -K $encrypted_099a44ce718c_key -iv $encrypted_099a44ce718c_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
  - mkdir config_jsons
  - tar xvf credentials.tar.gz -C config_jsons
# command to run tests
script:
  - make test
after_success:
  - coveralls
notifications:
  email: false